- name: Setup Server Environment
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Kubernetes tools
      apt:
        name: 
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes
